### ISSUE TITLE
Fix - Landing page smaller screen buttons hidden by partner logos

### ISSUE THREAD

**Issue by PBillingsby** [kempsterrrr/P3RKS#62]
When you decrease the width of the screen, the logo icons block the clickable parts of the two buttons (links).

For example:
![Screen Shot 2022-07-06 at 9 17 29 PM](https://user-images.githubusercontent.com/45179070/177690469-1a8a1e7c-1796-4f2c-8d6f-c884550c0a3c.png)

Everything to the right of "Offer" is not directing to its href.

**Comment by kempsterrrr** [comment]
Closing as done
